baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'The Daily Broadsheet'
theme = 'hugo-broadsheet'

# Performance optimizations
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  description = "A demonstration of the Broadsheet Hugo theme"
  tagline = "All the news that's fit to print"
  showReadingTime = true
  enableSearch = false

  [[params.footerLinks]]
    name = "About"
    url = "/about/"
  [[params.footerLinks]]
    name = "Contact"
    url = "/contact/"

[menu]
  [[menu.main]]
    name = "News"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
